### ISSUE TITLE
Springboot 2: Can not found: org.springframework.boot.bind.RelaxedPropertyResolver

### ISSUE THREAD

**Issue by developerworks** [apache/incubator-dubbo-spring-boot-project#112]
```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceAnnotationBeanPostProcessor' defined in class path resource [com/alibaba/boot/dubbo/autoconfigure/DubboAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate 
...
...
[com.alibaba.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationBeanPostProcessor]: Factory method 'serviceAnnotationBeanPostProcessor' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/bind/RelaxedPropertyResolver
...
...
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.bind.RelaxedPropertyResolver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 30 more
```

demo of the issue:
 
https://github.com/developerworks/dubbo-bug-demo-for-springboo2

Commands of re-produce the issue:

```
git clone https://github.com/developerworks/dubbo-bug-demo-for-springboo2
cd dubbo-bug-demo-for-springboo2
mvn spring-boot:run
```

## Spring-Boot-2.0-Migration-Guide

The `org.springframework.boot.bind` package is no longer available and is replaced by the new relaxed binding infrastructure.

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

**Comment by mercyblitz** [comment]
Try this one  : https://github.com/apache/incubator-dubbo-spring-boot-project/tree/0.2.0
And install https://github.com/mercyblitz/dubbo locally

**Comment by Hicham-ALAGAD** [comment]
But, if we passed directly to a versions > 1.5.X, and we need to use RelaxedPropertyResolver, so in this case, how we can orgnize that ?
