### ISSUE TITLE
Can it run in different versions

### ISSUE THREAD

**Issue by nxycdl** [apache/incubator-dubbo-spring-boot-project#119]
My SpringBoot（consumer） Dubbo version is 2.5.10 ， But my provider(old program) Dubbo version is 2.5.3 ，when I call provider method some error happen , I'm sure my provider is normal.
best
```
com.alibaba.dubbo.rpc.RpcException: No provider available from registry 192.168.200.2:2181 for service com.xxx.xxx.xxx.xxxServiceApi on consumer 192.168.86.1 use dubbo version 2.0.1, please check status of providers(disabled, not registered or in blacklist).
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:572)
	at com.alibaba.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:73)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:265)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:224)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
```

**Comment by nxycdl** [comment]
I'm sorry, I've got a mistake here
