### ISSUE TITLE
好几个朋友都在问多协议的配置，望能解答下，这个是很基本的功能。

### ISSUE THREAD

**Issue by 15168326318** [apache/incubator-dubbo-spring-boot-project#263]
![image](https://user-images.githubusercontent.com/38483933/44391556-c11bc200-a562-11e8-9c03-c25d68c0861b.png)
![image](https://user-images.githubusercontent.com/38483933/44391578-c973fd00-a562-11e8-8703-23ae5e8a50fc.png)
找不到协议。

**Comment by mercyblitz** [comment]
`@Service(protocol={"rest","dubbo"})` , `protocol` is a multiple value attribute

**Comment by fangQiangQiang** [comment]
@Service(protocol={"rest","dubbo"})
-----------
not fix

**Comment by fangQiangQiang** [comment]
@Service(protocol={"rest","dubbo"}) , protocol is a multiple value attribute
---------
not works !!!!!

**Comment by li-keli** [comment]
me too, no work, and quote us: ` A component required A bean named 'dubbo' that could not be found. `

**Comment by mercyblitz** [comment]
First, add these properties into your `application.properties`:

```properties
## Enable multiple config bindings
dubbo.config.multiple =true

## ProtocolConfig Bean
dubbo.protocols.dubbo.name = dubbo
dubbo.protocols.dubbo.port = 12345
dubbo.protocols.dubbo.status = server

dubbo.protocols.rest.name = rest
dubbo.protocols.rest.port = 8888
```

Second,  add the dependencies to your `pom.xml`:

```xml
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxrs</artifactId>
            <version>3.0.19.Final</version>
        </dependency>

        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>1.1.0.Final</version>
        </dependency>

        <dependency>
            <groupId>org.mortbay.jetty</groupId>
            <artifactId>jetty</artifactId>
            <version>6.1.26</version>
            <exclusions>
                <exclusion>
                    <groupId>org.mortbay.jetty</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Third, specify multiple protocols:

```java
@Service(
        version = "${demo.service.version}",
        protocol = {"dubbo", "rest"},
        registry = "${dubbo.registry.id}"
)
@Path("demo")
public class DefaultDemoService implements DemoService {

    @GET
    @Path("/say-hello")
    public String sayHello(@QueryParam("name") String name) {
        return "Hello, " + name + " (from Spring Boot)";
    }
}
```

Last, curl this REST URL:

```
$ curl http://localhost:8888/demo/say-hello?name=%E5%B0%8F%E9%A9%AC%E5%93%A5
Hello, 小马哥 (from Spring Boot)
```

**Comment by li-keli** [comment]
**mark**

I continue to in pom. Add the XML `javax.servlet-api` can normal use.

spring-boot version: `2.0.1`

```xml
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
    <version>4.0.1</version>
    <scope>provided</scope>
</dependency>
```

**Comment by li-keli** [comment]
@mercyblitz 马哥，According to your configuration, there you go. HTTP services are available externally, but there are new problems. Please give me some advice.

> Is it possible to add unit test samples to dubbo-spring-boot-samples?

**Problem description**
The multi-protocol is configured and registered in the registry, but the previous unit tests are all dead.

**Env**
* MacOS 10.14
* spring-boot-starter-parent 2.0.1.RELEASE
* dubbo-spring-boot-starter v0.2.0
* dubbo v2.6.5

**Provider**
```java
@Service(protocol = {"dubbo", "rest"})
public class CtripChannelServiceImpl implements CtripChannelService {

    private static final ApiLogger logger = ApiLoggerManager.INSTANCE.getLogger(CtripChannelServiceImpl.class);

    @GET
    @Path("/health")
    @Override
    public String health() {
        return "SUCCESS";
    }
}
```

**UnitTest**
```java
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import static org.junit.Assert.*;

/**
 * @Author: likeli
 * @Description:
 * @Data: Create in 2018-12-20 08:58
 * @Modificd_By:
 */
@SpringBootTest
@RunWith(SpringJUnit4ClassRunner.class)
public class CtripChannelServiceImplTest {

    @Autowired
    CtripChannelServiceImpl ctripChannelService;

    @Test
    public void health() {
        ctripChannelService.health();
        System.out.println("pass");
    }
}
```

**Error Message**
```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webFluxValidator' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.validation.Validator]: Factory method 'webFluxValidator' threw exception; nested exception is javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:138)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.validation.Validator]: Factory method 'webFluxValidator' threw exception; nested exception is javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 42 more
Caused by: javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:271)
	at org.springframework.boot.validation.MessageInterpolatorFactory.getObject(MessageInterpolatorFactory.java:53)
	at org.springframework.boot.autoconfigure.validation.ValidatorAdapter.create(ValidatorAdapter.java:138)
	at org.springframework.boot.autoconfigure.validation.ValidatorAdapter.getExistingOrCreate(ValidatorAdapter.java:119)
	at org.springframework.boot.autoconfigure.validation.ValidatorAdapter.get(ValidatorAdapter.java:111)
	at org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration.webFluxValidator(WebFluxAutoConfiguration.java:239)
	at org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration$$EnhancerBySpringCGLIB$$c4d5a1cd.CGLIB$webFluxValidator$1(<generated>)
	at org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration$$EnhancerBySpringCGLIB$$c4d5a1cd$$FastClassBySpringCGLIB$$7df97645.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration$$EnhancerBySpringCGLIB$$c4d5a1cd.webFluxValidator(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 43 more
```

**Comment by mercyblitz** [comment]
@li-keli Please add `hibernate-validator` into classpath

**Comment by zondahuman** [comment]
> First, add these properties into your `application.properties`:
> 
> ```ini
> ## Enable multiple config bindings
> dubbo.config.multiple =true
> 
> ## ProtocolConfig Bean
> dubbo.protocols.dubbo.name = dubbo
> dubbo.protocols.dubbo.port = 12345
> dubbo.protocols.dubbo.status = server
> 
> dubbo.protocols.rest.name = rest
> dubbo.protocols.rest.port = 8888
> ```
> 
> Second, add the dependencies to your `pom.xml`:
> 
> ```
>         <dependency>
>             <groupId>org.jboss.resteasy</groupId>
>             <artifactId>resteasy-jaxrs</artifactId>
>             <version>3.0.19.Final</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>javax.validation</groupId>
>             <artifactId>validation-api</artifactId>
>             <version>1.1.0.Final</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.mortbay.jetty</groupId>
>             <artifactId>jetty</artifactId>
>             <version>6.1.26</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>org.mortbay.jetty</groupId>
>                     <artifactId>servlet-api</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
> ```
> 
> Third, specify multiple protocols:
> 
> ```java
> @Service(
>         version = "${demo.service.version}",
>         protocol = {"dubbo", "rest"},
>         registry = "${dubbo.registry.id}"
> )
> @Path("demo")
> public class DefaultDemoService implements DemoService {
> 
>     @GET
>     @Path("/say-hello")
>     public String sayHello(@QueryParam("name") String name) {
>         return "Hello, " + name + " (from Spring Boot)";
>     }
> }
> ```
> 
> Last, curl this REST URL:
> 
> ```
> $ curl http://localhost:8888/demo/say-hello?name=%E5%B0%8F%E9%A9%AC%E5%93%A5
> Hello, 小马哥 (from Spring Boot)
> ```

这个rest默认是jetty，如果使用tomcat的话，怎么配置下，work不起来
