### ISSUE TITLE
集成shiro权限时，zookeeper端口号被奇怪指定为9090

### ISSUE THREAD

**Issue by fengzhentian** [apache/incubator-dubbo-spring-boot-project#283]
在consumer项目里，配置如下
# dubbo配置
dubbo:
  # 注册中心配置
  registry:
    protocol: zookeeper
    address: 127.0.0.1
    port: 2181

如果集成了shiro，我在自定义的OAuth2Realm类里，需要通过dubbo调用provider里的方法，就会报如下错误
我指定了2181端口，但是跑起来后执行的确下9090端口，将代码里@Reference的代码注释掉就正常了。。。

简要代码示例
@Component
public class OAuth2Realm extends AuthorizingRealm {
    @Reference
    private ShiroService shiroService;
}

返回错误信息

2018-09-20 10:51:00.492  WARN 9004 --- [127.0.0.1:9090)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

**Comment by fengzhentian** [comment]
通过尝试，修改为以下这种，就正常了，目前原因不清楚，请帮忙查看下原因

# dubbo配置
dubbo:
  # 注册中心配置
  registry:
    address: zookeeper://127.0.0.1:2181
