### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet

### ISSUE THREAD

**Issue by smileszx** [apache/incubator-dubbo-spring-boot-project#340]
How to solve this issue?
`2018-12-26 16:32:33.043  INFO 6960 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-26 16:32:33.052 ERROR 6960 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet
......
com.alibaba.boot.dubbo.demo.provider.bootstrap.DubboProviderDemo.main(DubboProviderDemo.java:38) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
	... 39 common frames omitted`

**Comment by smileszx** [comment]
How to start the project?

**Comment by mercyblitz** [comment]
Did you change code, e,g. `setWebApplicationType(WebApplicationType.WEB)` ?

**Comment by mercyblitz** [comment]
You can try : 
```java
        new SpringApplicationBuilder(DubboProviderDemo.class)
                .web(WebApplicationType.NONE)
                .run(args);
```

**Comment by shenzhuan** [comment]
好像没有用吧
