### ISSUE TITLE
dubbo + nacos 版本升级后服务无法注册成功

### ISSUE THREAD

**Issue by CjqDy** [apache/incubator-dubbo-spring-boot-project#490]
原来版本是 dubbo 2.6.5 + nacos 0.0.1  可以正常注册和消费
换成dubbo 2.7.1后  原来的包名不匹配的问题没有了 但是无法正常注册
只是替换了dubbo 及 nacos的版本，配置文件都没有改变，nacos客户端也是正常启动的
以下是错误信息：
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance. code:400 msg: dom not found: DEFAULT_GROUP@@providers:com.orange.service.DemoService

	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:186)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:294)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:275)
	at org.apache.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:155)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:474)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:153)
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:231)
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:160)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:194)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:106)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.orange.ProviderApplication.main(ProviderApplication.java:16)

**Comment by zxh19920616** [comment]
我也报这个错java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([:8848]) tried: failed to req API:http://:8848/nacos/v1/ns/instance. code:400 msg: dom not found: DEFAULT_GROUP@@blade-auth

**Comment by ralf0131** [comment]
Could you provide an example/steps to reproduce this issue?

**Comment by CjqDy** [comment]
> Could you provide an example/steps to reproduce this issue?

@ralf0131 我用的版本是 dubbo 2.7.1   dubbo-registry-nacos 2.7.1  nacos-client 1.0.0-RC3
这个是我在dubbo 和 nacos 的demo中使用的版本
debug了相关代码

在nacos-client 包 调用NamingProxy里的callServer方法  在进行到
HttpResult result = HttpClient.request(url, headers, params, "UTF-8", method);  发起请求的的时候
返回的result.code 为400  result.content为
dom not found: DEFAULT_GROUP@@providers:com.orange.demo.service.DemoService

所以怀疑是否是nacos-client版本存在问题

忘能告知

**Comment by CjqDy** [comment]
找到问题了  我只是升级了dubbo和nacos-client到2.7.1 ，但是nacos-server的版本没有更新还是0.0.9的 升级到1.0.0就行了
