### ISSUE TITLE
log bind  error 

### ISSUE THREAD

**Issue by tangzhe7** [apache/incubator-dubbo-spring-boot-project#505]
### pom.xml
```
<dubbo-version>2.7.0</dubbo-version>
<dubbo-start-version>2.7.0</dubbo-start-version>
            <dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>${dubbo-start-version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo</artifactId>
			<version>${dubbo-version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
### exception

```
2019-04-28 17:52:049 ERROR o.s.b.SpringApplication -Application startup failed
java.lang.NoSuchMethodError: com.alibaba.dubbo.common.logger.LoggerAdapter.getLogger(Ljava/lang/String;)Lcom/alibaba/dubbo/common/logger/Logger;
	at com.alibaba.dubbo.common.logger.LoggerFactory.setLoggerAdapter(LoggerFactory.java:83)
	at com.alibaba.dubbo.common.logger.LoggerFactory.<clinit>(LoggerFactory.java:43)
	at com.alibaba.dubbo.common.Version.<clinit>(Version.java:35)
	at com.alibaba.boot.dubbo.context.event.WelcomeLogoApplicationListener.buildBannerText(WelcomeLogoApplicationListener.java:70)
	at com.alibaba.boot.dubbo.context.event.WelcomeLogoApplicationListener.onApplicationEvent(WelcomeLogoApplicationListener.java:52)
	at com.alibaba.boot.dubbo.context.event.WelcomeLogoApplicationListener.onApplicationEvent(WelcomeLogoApplicationListener.java:39)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.qingread.vip.QingreadTenVipApplication.main(QingreadTenVipApplication.java:40)
```
can anyone help?

**Comment by tangzhe7** [comment]
dubbo dependencies was repeat

**Comment by Scalaaaaaa** [comment]
如 @tangzhe7 所说,dubbo重复了<groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo</artifactId>,  右击你的项目pom文件内空白处,Diagrams->Show Dependencies,  然后放大找到dubbo,会有多个dubbo,这时候,双击dubbo,就能找到引用这个jar的所在pom的位置,然后就能找到哪里重复引用了,如果是自己的pom重复引用,只保留一个即可,如果是pom套pom,则使用<exclusions>剔除即可
