### ISSUE TITLE
服务提供者检查问题check=false无效

### ISSUE THREAD

**Issue by Skqing** [apache/incubator-dubbo-spring-boot-project#516]
版本信息：
```
org.springframework.boot:2.1.5.RELEASE

<dubbo.version>2.7.1</dubbo.version>
<dubbo-spring-boot-starter.version>2.7.1</dubbo-spring-boot-starter.version>
```

配置信息：
```
#Dubbo配置
dubbo:
  registry:
    address: zookeeper://192.168.31.79:2181
    client: zkclient
    check: false
  consumer:
    check: false
```

调用信息：
```
@SpringBootApplication
public class NewDemoConsumerApplication {

    @Reference(version = "${demo.service.version}", check = false)
    private DubboTestService dubboTestService;

    public static void main(String[] args) {
        SpringApplication.run(NewDemoConsumerApplication.class, args);
    }

    @Bean
    public ApplicationRunner runner() {
        return args -> {
            System.out.println(dubboTestService.sayHello("hct"));
        };
    }

}
```

报错信息：
```
2019-05-21 15:21:56.380 DEBUG 16132 --- [           main] o.s.boot.diagnostics.FailureAnalyzers    : FailureAnalyzer org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer@153f66e7 failed

java.lang.TypeNotPresentException: Type org.springframework.jdbc.CannotGetJdbcConnectionException not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:1.8.0_152]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:1.8.0_152]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.8.0_152]
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:1.8.0_152]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:1.8.0_152]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.8.0_152]
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90) ~[na:1.8.0_152]
	at java.lang.Class.getGenericSuperclass(Class.java:777) ~[na:1.8.0_152]
	at org.springframework.core.ResolvableType.getSuperType(ResolvableType.java:466) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.core.ResolvableType.as(ResolvableType.java:455) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.core.ResolvableType.forClass(ResolvableType.java:1037) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.diagnostics.AbstractFailureAnalyzer.getCauseType(AbstractFailureAnalyzer.java:58) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.diagnostics.AbstractFailureAnalyzer.analyze(AbstractFailureAnalyzer.java:34) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.diagnostics.FailureAnalyzers.analyze(FailureAnalyzers.java:114) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.diagnostics.FailureAnalyzers.reportException(FailureAnalyzers.java:107) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:848) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:832) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at com.hct.example.consumer.NewDemoConsumerApplication.main(NewDemoConsumerApplication.java:17) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.CannotGetJdbcConnectionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_152]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_152]
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[na:1.8.0_152]
	... 20 common frames omitted

2019-05-21 15:21:56.382 ERROR 16132 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at com.hct.example.consumer.NewDemoConsumerApplication.main(NewDemoConsumerApplication.java:17) [classes/:na]
Caused by: java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy48.sayHello(Unknown Source) ~[na:na]
	at com.hct.example.consumer.NewDemoConsumerApplication.lambda$runner$0(NewDemoConsumerApplication.java:23) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	... 5 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.invoke(ReferenceAnnotationBeanPostProcessor.java:158) ~[dubbo-2.7.0.jar:2.7.0]
	... 8 common frames omitted
Caused by: org.apache.dubbo.rpc.RpcException: No provider available from registry 192.168.31.79:2181 for service com.hct.example.client.DubboTestService:1.0.0 on consumer 10.2.1.93 use dubbo version 2.7.0, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:522) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:82) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:274) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:238) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java) ~[dubbo-2.7.0.jar:2.7.0]
	... 13 common frames omitted

2019-05-21 15:21:56.384  INFO 16132 --- [           main] .b.c.e.AwaitingNonWebApplicationListener :  [Dubbo] Current Spring Boot Application is about to shutdown...
2019-05-21 15:21:56.519  INFO 16132 --- [           main] org.apache.zookeeper.ZooKeeper           : Session: 0x16a00da955f0296 closed
2019-05-21 15:21:56.519  INFO 16132 --- [r-1-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x16a00da955f0296
2019-05-21 15:21:57.594  INFO 16132 --- [MessageThread_1] com.hct.example.consumer.mq.MyConsumer2  : received orderPaidEvent: OrderPaidEvent(orderId=T_001, paidMoney=88.00)
2019-05-21 15:21:57.883  INFO 16132 --- [           main] a.r.s.s.DefaultRocketMQListenerContainer : container destroyed, DefaultRocketMQListenerContainer{consumerGroup='my-consumer_test-topic-2', nameServer='192.168.31.81:9876', topic='test-topic-2', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING}
2019-05-21 15:21:57.884  INFO 16132 --- [           main] a.r.s.s.DefaultRocketMQListenerContainer : container destroyed, DefaultRocketMQListenerContainer{consumerGroup='my-consumer_test-topic-1', nameServer='192.168.31.81:9876', topic='test-topic-1', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING}
2019-05-21 15:21:57.886  INFO 16132 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : org.apache.dubbo.common.bytecode.proxy0@49dbaaf3 was destroying!
2019-05-21 15:21:57.886  INFO 16132 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
```

**Comment by Skqing** [comment]
升级到2.7.1问题解决
