### ISSUE TITLE
How to Generic reference

### ISSUE THREAD

**Issue by zeng54088** [apache/incubator-dubbo-spring-boot-project#99]
DubboConfiguration

@Configuration
public class DubboConfiguration {

    @Bean
    public ReferenceBean referenceBean(){
        ReferenceBean referenceConfig=new ReferenceBean();
        referenceConfig.setInterface("com.alibaba.boot.dubbo.demo.consumer.DemoService");
        referenceConfig.setId("fzjh");
        return referenceConfig;

    }
}

but Exception no bean
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'fzjh' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:698) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1175) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]

**Comment by mercyblitz** [comment]
How to reference "fzjh" Bean?

**Comment by mercyblitz** [comment]
Please change the Bean definition to `@Bean("fzjh")`
